global:
  resolve_timeout: 5m

route:
  receiver: pagerduty-notifications
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  routes:
    - matchers:
        - severity="critical"
      receiver: pagerduty-notifications

receivers:
  - name: pagerduty-notifications
    pagerduty_configs:
      - service_key: <PAGERDUTY_INTEGRATION_KEY>
        severity: critical
